# Generated by Django 5.2.17 on 2026-08-20 19:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "standard_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "variable_unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Direct variable production cost per newly replenished unit.",
                        max_digits=12,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                ("code", models.SlugField(max_length=40, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("OPEN", "Open for registration"),
                            ("ACTIVE", "Active"),
                            ("COMPLETE", "Complete"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "current_year",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ],
                    ),
                ),
                (
                    "current_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                        ],
                        default=8,
                        help_text="August represents the annual planning stage before September operations begin.",
                    ),
                ),
                ("registration_deadline", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GameMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Game administrator"),
                            ("PLAYER", "VP Sales & Operations"),
                        ],
                        default="PLAYER",
                        max_length=10,
                    ),
                ),
                ("team_name", models.CharField(blank=True, max_length=120)),
                (
                    "results_summary_reached",
                    models.BooleanField(
                        default=False,
                        help_text="True after the player completes the final-year review and opens the combined simulation results summary.",
                    ),
                ),
                (
                    "last_reviewed_year",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Highest simulation year whose year-end Board review the player has completed. Zero means no annual review has yet been completed.",
                        validators=[django.core.validators.MaxValueValidator(3)],
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="simulation.game",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["game", "role", "user__username"],
            },
        ),
        migrations.AddField(
            model_name="game",
            name="users",
            field=models.ManyToManyField(
                related_name="strategy_games",
                through="simulation.GameMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="MonthlyDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                        ]
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_finalized", models.BooleanField(default=False)),
                (
                    "manufacturing_overhead",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Unabsorbed annual fixed manufacturing cost recognized in the final month. Zero outside August.",
                        max_digits=14,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="simulation.gamemembership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beginning_inventory_units",
                    models.PositiveIntegerField(
                        default=0, help_text="Inventory carried into the month."
                    ),
                ),
                (
                    "replenishment_units",
                    models.PositiveIntegerField(
                        default=0, help_text="New units replenished for the month."
                    ),
                ),
                (
                    "available_inventory_units",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Beginning inventory plus new replenishment.",
                    ),
                ),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("true_demand_units", models.PositiveIntegerField(default=0)),
                ("adjusted_demand_units", models.PositiveIntegerField(default=0)),
                ("units_sold", models.PositiveIntegerField(default=0)),
                ("ending_inventory_units", models.PositiveIntegerField(default=0)),
                ("lost_sales_units", models.PositiveIntegerField(default=0)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "variable_production_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "labor_fixed_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "maintenance_fixed_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "total_production_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "holding_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "inventory_write_off",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Final-month write-off of ending inventory at full production cost. Zero outside August.",
                        max_digits=14,
                    ),
                ),
                (
                    "sales_credit_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "monthly_decision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_decisions",
                        to="simulation.monthlydecision",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="simulation.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year_number",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(3),
                        ]
                    ),
                ),
                (
                    "revenue_target",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Baseline board-established revenue target. Year 1 uses this value directly. Years 2 and 3 may allow the player to select a higher target.",
                        max_digits=14,
                    ),
                ),
                (
                    "operating_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Baseline annual operating budget. Year 1 uses this value directly. Years 2 and 3 may use a player-selected budget associated with the selected revenue commitment.",
                        max_digits=14,
                    ),
                ),
                (
                    "monthly_interest_rate",
                    models.DecimalField(
                        decimal_places=5,
                        default=Decimal("0.01000"),
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "initial_inventory_units",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Beginning September inventory supplied for each product.",
                    ),
                ),
                (
                    "labor_fixed_cost_share",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.60"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "maintenance_fixed_cost_share",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.40"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenario_years",
                        to="simulation.game",
                    ),
                ),
            ],
            options={
                "ordering": ["year_number"],
            },
        ),
        migrations.CreateModel(
            name="PlayerYearScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "operating_expense",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "sales_credit_collected",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("lost_sales_units", models.PositiveIntegerField(default=0)),
                (
                    "ending_inventory_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="year_scores",
                        to="simulation.gamemembership",
                    ),
                ),
                (
                    "scenario_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_scores",
                        to="simulation.scenarioyear",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
            },
        ),
        migrations.AddField(
            model_name="monthlydecision",
            name="scenario_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decisions",
                to="simulation.scenarioyear",
            ),
        ),
        migrations.CreateModel(
            name="ForecastSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                        ],
                        help_text="Month in which the forecast became available. August is the initial annual-planning forecast.",
                    ),
                ),
                (
                    "forecast_month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                        ]
                    ),
                ),
                ("forecast_units", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="forecast_snapshots",
                        to="simulation.product",
                    ),
                ),
                (
                    "scenario_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecast_snapshots",
                        to="simulation.scenarioyear",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemandValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                        ]
                    ),
                ),
                ("ideal_demand", models.PositiveIntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="true_demands",
                        to="simulation.product",
                    ),
                ),
                (
                    "scenario_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demand_values",
                        to="simulation.scenarioyear",
                    ),
                ),
            ],
            options={
                "ordering": ["scenario_year", "product", "month"],
            },
        ),
        migrations.CreateModel(
            name="AnnualPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selected_revenue_target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Player-selected annual revenue commitment for Years 2 and 3.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "selected_operating_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Operating budget associated with the player-selected revenue commitment for Years 2 and 3.",
                        max_digits=14,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "sales_credit_rate",
                    models.DecimalField(
                        choices=[
                            (Decimal("0.05"), "5% — Tight pricing authority"),
                            (Decimal("0.10"), "10% — Moderate pricing authority"),
                            (Decimal("0.20"), "20% — Broad pricing authority"),
                        ],
                        decimal_places=2,
                        default=Decimal("0.10"),
                        max_digits=4,
                    ),
                ),
                ("skip_maintenance", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_plans",
                        to="simulation.gamemembership",
                    ),
                ),
                (
                    "scenario_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annual_plans",
                        to="simulation.scenarioyear",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="gamemembership",
            constraint=models.UniqueConstraint(
                fields=("game", "user"), name="unique_game_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdecision",
            constraint=models.UniqueConstraint(
                fields=("monthly_decision", "product"), name="unique_decision_product"
            ),
        ),
        migrations.AddConstraint(
            model_name="scenarioyear",
            constraint=models.UniqueConstraint(
                fields=("game", "year_number"), name="unique_game_year"
            ),
        ),
        migrations.AddConstraint(
            model_name="playeryearscore",
            constraint=models.UniqueConstraint(
                fields=("membership", "scenario_year"), name="unique_player_year_score"
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlydecision",
            constraint=models.UniqueConstraint(
                fields=("membership", "scenario_year", "month"),
                name="unique_monthly_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="forecastsnapshot",
            constraint=models.UniqueConstraint(
                fields=("scenario_year", "product", "base_month", "forecast_month"),
                name="unique_forecast_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandvalue",
            constraint=models.UniqueConstraint(
                fields=("scenario_year", "product", "month"), name="unique_true_demand"
            ),
        ),
        migrations.AddConstraint(
            model_name="annualplan",
            constraint=models.UniqueConstraint(
                fields=("membership", "scenario_year"),
                name="unique_annual_plan_membership_year",
            ),
        ),
    ]
