# Generated by Django 5.2.3 on 2026-08-21 16:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("simulation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_redo_year_1",
                    models.BooleanField(
                        default=True,
                        help_text="Allow players to restart Year 1 after completing it.",
                    ),
                ),
                (
                    "allow_redo_year_2",
                    models.BooleanField(
                        default=True,
                        help_text="Allow players to restart Year 2 after completing it.",
                    ),
                ),
                (
                    "allow_full_restart",
                    models.BooleanField(
                        default=True,
                        help_text="Allow players to restart the complete simulation from the beginning of Year 1.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="InstructorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=180)),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("PRACTITIONER", "Practitioner"),
                            ("EXECUTIVE_DIRECTOR", "Executive Director"),
                            ("LECTURER", "Lecturer"),
                            ("ASSISTANT_PROFESSOR", "Assistant Professor"),
                            ("ASSOCIATE_PROFESSOR", "Associate Professor"),
                            ("PROFESSOR", "Professor"),
                            ("ADJUNCT_PROFESSOR", "Adjunct Professor"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["institution", "user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="YearAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_number",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("COMPLETE", "Complete"),
                            ("ABANDONED", "Abandoned"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=True,
                        help_text="True for the attempt that currently governs the player's progress in this simulation year.",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": [
                    "membership",
                    "scenario_year__year_number",
                    "-attempt_number",
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="annualplan",
            name="unique_annual_plan_membership_year",
        ),
        migrations.RemoveConstraint(
            model_name="monthlydecision",
            name="unique_monthly_decision",
        ),
        migrations.RemoveConstraint(
            model_name="playeryearscore",
            name="unique_player_year_score",
        ),
        migrations.AddField(
            model_name="game",
            name="invite_token",
            field=models.UUIDField(
                blank=True,
                editable=False,
                help_text="Private invitation token used to register players for this game.",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="gamemembership",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Instructor"), ("PLAYER", "VP Sales & Operations")],
                default="PLAYER",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="gamesettings",
            name="game",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="design_settings",
                to="simulation.game",
            ),
        ),
        migrations.AddField(
            model_name="instructorprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructor_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="yearattempt",
            name="membership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="year_attempts",
                to="simulation.gamemembership",
            ),
        ),
        migrations.AddField(
            model_name="yearattempt",
            name="scenario_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attempts",
                to="simulation.scenarioyear",
            ),
        ),
        migrations.AddField(
            model_name="annualplan",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                help_text="Year attempt this annual plan belongs to. Null is retained for legacy records.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annual_plans",
                to="simulation.yearattempt",
            ),
        ),
        migrations.AddField(
            model_name="monthlydecision",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                help_text="Year attempt this monthly decision belongs to. Null is retained for legacy records.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="monthly_decisions",
                to="simulation.yearattempt",
            ),
        ),
        migrations.AddField(
            model_name="playeryearscore",
            name="attempt",
            field=models.OneToOneField(
                blank=True,
                help_text="Year attempt summarized by this score. Null is retained for legacy records.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="year_score",
                to="simulation.yearattempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="annualplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", True)),
                fields=("membership", "scenario_year"),
                name="unique_legacy_annual_plan_membership_year",
            ),
        ),
        migrations.AddConstraint(
            model_name="annualplan",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", False)),
                fields=("attempt",),
                name="unique_annual_plan_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlydecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", True)),
                fields=("membership", "scenario_year", "month"),
                name="unique_legacy_monthly_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="monthlydecision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", False)),
                fields=("attempt", "month"),
                name="unique_attempt_monthly_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="playeryearscore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", True)),
                fields=("membership", "scenario_year"),
                name="unique_legacy_player_year_score",
            ),
        ),
        migrations.AddConstraint(
            model_name="yearattempt",
            constraint=models.UniqueConstraint(
                fields=("membership", "scenario_year", "attempt_number"),
                name="unique_year_attempt_number",
            ),
        ),
        migrations.AddConstraint(
            model_name="yearattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("membership", "scenario_year"),
                name="unique_current_year_attempt",
            ),
        ),
    ]
